### ISSUE TITLE
Update to new Rollup version

### ISSUE THREAD

**Issue by codewizard-dt** [juliendargelos/rollup-plugin-emit-files#294]
Rollup is now at version ^3.2

Any chance to update this package to handle the new version?

**Comment by juliendargelos** [comment]
Hi, I will take a look at it, thanks for raising this issue

**Comment by juliendargelos** [comment]
The plugin should now be compatible with rollup 3.x, you will have to upgrade to rollup-plugin-emit-files `^2.0.0`

**Comment by codewizard-dt** [comment]
Awesome thank you!
